spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        implicit_naming_strategy: to.lova.spring.blaze.ImplicitNamingStrategyComponentPathJoinTable
        ejb:
          metamodel:
            population: enabled
      org.hibernate.envers:
        store_data_at_delete: true
        global_with_modified_flag: true
        audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
        audit_strategy_validity_store_revend_timestamp: true
