spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        implicit_naming_strategy: to.lova.spring.blaze.ImplicitNamingStrategyComponentPathJoinTable
